### ISSUE TITLE
REXTwoWayMarket Tests and Migration to typescript

### ISSUE THREAD

**Issue by vaibhavgeek** [Ricochet-Exchange/ricochet-protocol#67] opened 2022-01-31 14:40 UTC
This issue is similar and there has been lot of work put into making common code (abstraction) for tests. Migrate the code to typescript using superlfuid `sdk-core` package, common `misc/` folder libraries and well documented code.

**Comment by josealonso** [comment] 2022-01-31 17:16
Working on this

**Comment by josealonso** [comment] 2022-02-09 11:02
I still need to coordinate with @vaibhavgeek for this task.

**Comment by josealonso** [comment] 2022-02-17 00:04
@mikeghen said on discord ```type script tests are definitely a priority, the tests are so long and my most common errors would be caught with static typing```.

**Comment by josealonso** [comment] 2022-02-20 01:03
Most of the code for the TC `"should distribute tokens to streamers"` is now migrated to the Superfluid Typescript SDK, a.k. **sdk-core**. But there's a nasty `Execute Transaction Error` when the start case starts. I don't know if this error is caused by the Polygon network or by my code, because the error message is not very meaningful:
```
  1) REXTwoWayMarket
       should distribute tokens to streamers:
     Execute Transaction Error - There was an error executing the transaction: {"type":"POPULATE_TRANSACTION","errorObject":{"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"stackTrace":[{"type":2,"address":{"type":"Buffer","data":[62,20,220,27,19,196,136,168,213,211,16,145,135,128,201,131,189,89,130,231]}},{"type":2,"address":{"type":"Buffer","data":[62,20,220,27,19,196,136,168,213,211,16,145,135,128,201,131,189,89,130,231]}},{"type":2,"address":{"type":"Buffer","data":[176,170,187,164,178,120,58,114,197,41,86,205,239,98,212,56,236,162,215,161]}},{"type":18,"address":{"type":"Buffer","data":[176,170,187,164,178,120,58,114,197,41,86,205,239,98,212,56,236,162,215,161]},"message":{"value":{"type":"Buffer","data":[8,195,121,160,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,73,68,65,58,32,69,95,78,79,95,73,78,68,69,88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"_selector":"08c379a0"}}]},"tx":{"data":"0x39255d5b000000000000000000000000b0aabba4b2783a72c52956cdef62d438eca2d7a10000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000a4acf4a6c200000000000000000000000027e1e4e6bc79d93032abef01025811b7e4727e85000000000000000000000000baf5e9a1a8659578263d6fbfa0d41f909321d450000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","to":{},"from":"0x9f348cdD00dcD61EE7917695D2157ef6af2d7b9B","type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0xc7e291c2"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x9502f900"},"nonce":{},"gasLimit":{},"chainId":{}}},"message":"Populate Transaction Error - There was an error populating the transaction: {\"reason\":\"cannot estimate gas; transaction may fail or may require manual gas limit\",\"code\":\"UNPREDICTABLE_GAS_LIMIT\",\"error\":{\"stackTrace\":[{\"type\":2,\"address\":{\"type\":\"Buffer\",\"data\":[62,20,220,27,19,196,136,168,213,211,16,145,135,128,201,131,189,89,130,231]}},{\"type\":2,\"address\":{\"type\":\"Buffer\",\"data\":[62,20,220,27,19,196,136,168,213,211,16,145,135,128,201,131,189,89,130,231]}},{\"type\":2,\"address\":{\"type\":\"Buffer\",\"data\":[176,170,187,164,178,120,58,114,197,41,86,205,239,98,212,56,236,162,215,161]}},{\"type\":18,\"address\":{\"type\":\"Buffer\",\"data\":[176,170,187,164,178,120,58,114,197,41,86,205,239,98,212,56,236,162,215,161]},\"message\":{\"value\":{\"type\":\"Buffer\",\"data\":[8,195,121,160,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,73,68,65,58,32,69,95,78,79,95,73,78,68,69,88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},\"_selector\":\"08c379a0\"}}]},\"tx\":{\"data\":\"0x39255d5b000000000000000000000000b0aabba4b2783a72c52956cdef62d438eca2d7a10000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000a4acf4a6c200000000000000000000000027e1e4e6bc79d93032abef01025811b7e4727e85000000000000000000000000baf5e9a1a8659578263d6fbfa0d41f909321d450000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",\"to\":{},\"from\":\"0x9f348cdD00dcD61EE7917695D2157ef6af2d7b9B\",\"type\":2,\"maxFeePerGas\":{\"type\":\"BigNumber\",\"hex\":\"0xc7e291c2\"},\"maxPriorityFeePerGas\":{\"type\":\"BigNumber\",\"hex\":\"0x9502f900\"},\"nonce\":{},\"gasLimit\":{},\"chainId\":{}}}"}
```

**Comment by josealonso** [comment] 2022-02-20 01:06
The initialization (the *beforeEach* block) is working fine:
```
  REXTwoWayMarket
============ Right after initSuperfluid() ==================
address 0x3226C9EaC0379F04Ba2b1E1e1fcD52ac26309aeA
resigration ?? key testKey-1645317491055
============ Right after sfRegistrationKey() ==================
=========== Deployed REXReferral ============
Deploying REXTwoWayMarket...
=========== Deployed REXTwoWayMarket ============
oraclePrice:  2749050000
RIC oraclePrice:  636267
=========== Updated the oracles ============
index 0
distToken 0xcaa7349cea390f89641fe306d93591f87595dc1f
index 1
distToken 0x27e1e4e6bc79d93032abef01025811b7e4727e85
=========== Initialized TwoWayMarket ============
index 2
distToken 0x263026e7e53dbfdce5ae55ade22493f828922965
index 3
distToken 0x263026e7e53dbfdce5ae55ade22493f828922965
========== Initialized subsidies ===========
====== Test Case started ==========================

    1) should distribute tokens to streamers

true
```

**Comment by josealonso** [comment] 2022-03-08 01:01
Checked the `transfer` method is working, but not `createFlow`. My thanks to @vaibhavgeek and @rashtrakoff.

**Comment by josealonso** [comment] 2022-03-09 15:51
First assertions passing, but the call to `_rexReferral` in `RexMarket.sol` has been commented.

**Comment by josealonso** [comment] 2022-03-15 17:39
The call to `_rexReferral` is working, but I have problems to choose the ETHX whale address in polygonscan.

**Comment by josealonso** [comment] 2022-03-20 23:44
Mostly working now. The only thing left to do is commenting out the code related to the **delta** function, I don't know what that function does.

**Comment by josealonso** [comment] 2022-03-23 19:10
After @mikeghen's help, I consider this PR is ready to be merged.

**Comment by josealonso** [comment] 2022-03-23 22:25
New PR created, waiting for review.

**Closed** 2022-03-28 22:24 UTC
Labels: $5000 bounty
